
# Splits elevation zones into temperature zones.

# These temperature zones are then later split into different
# precipitation zones by the distribute_precipitation_zones.yml file.
# Zones unaffected by precipitation such oceanic, coastal, and
# polar as are handled in the distribute_variants.yml file instead.

temperature-map: &temperature-map
  dimensions: 2
  type: FBM
  octaves: 2
  sampler:
    type: OPEN_SIMPLEX_2
    frequency: 1 / ${meta.yml:biome-distribution.temperature-scale} / ${meta.yml:biome-distribution.global-scale}
    salt: 53

stages:
  - type: REPLACE_LIST
    sampler: *temperature-map
    
    default-from: deep-ocean
    default-to:
      - deep-ocean-tropical: 5
      - deep-ocean-subtropical: 4
      - deep-ocean-temperate: 6
      - deep-ocean-boreal: 4
      - deep-ocean-polar: 5
    
    to:

      ocean:
        - ocean-tropical: 5
        - ocean-subtropical: 4
        - ocean-temperate: 6
        - ocean-boreal: 4
        - ocean-polar: 5
  
      coast-flat:
        - coast-flat-tropical: 5
        - coast-flat-subtropical: 4
        - coast-flat-temperate: 6
        - coast-flat-boreal: 4
        - coast-flat-polar: 5
  
      coast-hills-small:
        - coast-hills-small-tropical: 5
        - coast-hills-small-subtropical: 4
        - coast-hills-small-temperate: 6
        - coast-hills-small-boreal: 4
        - coast-hills-small-polar: 5
  
      coast-hills-large:
        - coast-hills-large-tropical: 5
        - coast-hills-large-subtropical: 4
        - coast-hills-large-temperate: 6
        - coast-hills-large-boreal: 4
        - coast-hills-large-polar: 5
  
      coast-mountains-small:
        - coast-mountains-small-tropical: 5
        - coast-mountains-small-subtropical: 4
        - coast-mountains-small-temperate: 6
        - coast-mountains-small-boreal: 4
        - coast-mountains-small-polar: 5
  
      coast-mountains-large:
        - coast-mountains-large-tropical: 5
        - coast-mountains-large-subtropical: 4
        - coast-mountains-large-temperate: 6
        - coast-mountains-large-boreal: 4
        - coast-mountains-large-polar: 5
  
      flat:
        - flat-tropical: 5
        - flat-subtropical: 4
        - flat-temperate: 6
        - flat-boreal: 4
        - flat-polar: 5
  
      hills-small:
        - hills-small-tropical: 5
        - hills-small-subtropical: 4
        - hills-small-temperate: 6
        - hills-small-boreal: 4
        - hills-small-polar: 5

      hills-large:
        - hills-large-tropical: 5
        - hills-large-subtropical: 4
        - hills-large-temperate: 6
        - hills-large-boreal: 4
        - hills-large-polar: 5

      mountains-small:
        - mountains-small-tropical: 5
        - mountains-small-subtropical: 4
        - mountains-small-temperate: 6
        - mountains-small-boreal: 4
        - mountains-small-polar: 5

      mountains-large:
        - mountains-large-tropical: 5
        - mountains-large-subtropical: 4
        - mountains-large-temperate: 6
        - mountains-large-boreal: 4
        - mountains-large-polar: 5