stages:
  - type: REPLACE_LIST
    default-from: coast-hills-small
    default-to:
      - coast-hills-small: 2
      - coast-flat: 1
    to:
      coast-hills-large:
        - coast-hills-large: 2
        - coast-hills-small: 1
        - coast-flat: 1
      coast-mountains-small:
        - coast-mountains-small: 6
        - coast-hills-large: 1
        - coast-hills-small: 1
        - coast-flat: 6
      coast-mountains-large:
        - coast-mountains-large: 6
        - coast-hills-large: 1
        - coast-hills-small: 1
        - coast-flat: 6
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.1 / ${meta.yml:biome-distribution.global-scale}
      salt: 9129
